default:
smdba: --tags @smdba
spacecmd: --tags @spacecmd
spacewalk_utils: --tags @spacewalk_utils
visualization: --tags @visualization
notification_message: --tags @notification_message
virtual_host_manager: --tags @virtual_host_manager
subscription_matching: --tags @subscription_matching
formulas: --tags @formulas
sp_migration: --tags @sp_migration
cve_audit: --tags @cve_audit
onboarding: --tags @onboarding
content_lifecycle_management: --tags @content_lifecycle_management
res: --tags @res
recurring_actions: --tags @recurring_actions
maintenance_windows: --tags @maintenance_windows
cluster_management: --tags @cluster_management
building_container_images: --tags @building_container_images
kubernetes_integration: --tags @kubernetes_integration
openscap: --tags @openscap
ubuntu: --tags @ubuntu
action_chains: --tags @action_chains
salt_ssh: --tags @salt_ssh
tomcat: --tags @tomcat
changing_software_channels: --tags @changing_software_channels
monitoring: --tags @monitoring
salt: --tags @salt
cobbler: --tags @cobbler
sumatoolbox: --tags @sumatoolbox
virtualization: --tags @virtualization
hub: --tags @hub
retail: --tags @retail
configuration_channels: --tags @configuration_channels
content_staging: --tags @content_staging
proxy: --tags @proxy
traditional_client: --tags @traditional_client
xmlrpc: --tags @xmlrpc
power_management: --tags @power_management